### ISSUE TITLE
Add on failed on Startup, Issue with AddCards object missing reject attribute (Anki 23.10.1)

### ISSUE THREAD

**Issue by ryanzyi** [DarkTrick/AnkiTagSelector#4]
Anki TagSelector V2 fails on startup. I'm open to helping if I could get some guidance with contributing. I know Python, but I have never contributed to other's projects, but I am interested in doing so!

Here's the debug info:

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-14 00:00:00

When loading TagSelectorV2:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1022577188\__init__.py", line 806, in main_wrapFunctions
    AddCards._reject = wrap(AddCards._reject, main_onMaybeCloseAddCardsDialog,"before")
AttributeError: type object 'AddCards' has no attribute '_reject'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1022577188\__init__.py", line 842, in <module>
    main_wrapFunctions()
  File "C:\Users\user\AppData\Roaming\Anki2\addons21\1022577188\__init__.py", line 811, in main_wrapFunctions
    AddCards.reject = wrap(AddCards.reject, main_onMaybeCloseAddCardsDialog,"before")
AttributeError: type object 'AddCards' has no attribute 'reject'

**Comment by DarkTrick** [comment]
Thank you for reporting. I won't be able to fix this soon. If you can fix it, I'd be happy to integrate the fix.

### Why this (probably) happens

Anki changed it's internal structure. The "AddCards" object used to have a "_reject" method. The TagSelector need to use that in order to function properly for some use cases in regard of card adding. 

How to fix: 
Figure out...
1. What was the reason the tag selector needed the _reject method. Derive test cases from there.
2. Find an alternative and fix the code.
3. Test the code, clean the code, test the code, Pull Request.

**Comment by DarkTrick** [comment]
Fixed with [version 24.6.3.1](https://github.com/DarkTrick/AnkiTagSelector/releases/tag/v24.6.3.1).
